### ISSUE TITLE
Loading basic weakness error

### ISSUE THREAD

**Issue by Sarseth** [GeckoTH/arkham-horror#104]
Octgn couldnt load the deck:
Details:
(translated by me)
"Given key could not be found in dictionary"

3.1.294.0 version

**Comment by rushl** [comment]
Can we get some additional information? Such as:

- Which cards are in your deck?
- Is this a deck exported from ArkhamDB?
- I'm assuming this is a player deck. If not, which?

Thanks!

**Comment by Sarseth** [comment]
Hmm, after while I think I am using it wrongly.
1. Any.. does not matter, since I click "Game/load deck" and search for Arkham Horror - The Card Game\01 - Core\Basic Weaknesses.o8d

Is it supposed to work this way or another? Like deck building only purpose?

**Comment by rushl** [comment]
It should load like a regular deck. Are you unable to load any deck? Can you load a player deck?

**Comment by Sarseth** [comment]
I am able to load all decks from Core folder, except the weaknesses. In two different machines and two version of windows tested, win7 and win10.
I am able to load this deck in deck builder thou! But not in game.

**Comment by rushl** [comment]
This issue is fixed with 9e8674e. Also, note that you can load weaknesses by opening the Basic Weakness deck slot, or by right-clicking in your Hand area and selecting "Draw Basic Weakness".
