### ISSUE TITLE
Phase automation

### ISSUE THREAD

**Issue by Radanisa** [GeckoTH/arkham-horror#105]
When I pulse F12, the program locks in the step between Upkeep and Mythos phase. I did not do it before.

**Comment by rushl** [comment]
OCTGN version #3.1.296.0 made extensive changes to the Phase system. For now, once you've used F12 to reach the end of a round, you then use the green arrow by your name (just above your hand of cards) to advance to the next round. You can then use F12 as usual. 

We may be able to return the old functionality at some point, if possible. I'm not sure if OCTGN has left that ability in after their update.

**Comment by Radanisa** [comment]
Thanks!!

**Comment by brine** [comment]
any changes that were made should be reversible using the new phase controls that were added in that update
