### ISSUE TITLE
Location missing in the Miskatonic Museum

### ISSUE THREAD

**Issue by wjw01** [GeckoTH/arkham-horror#114]
I don't think this has been reported yet. But in the Miskatonic Museum there are 2 copies of the Restricted Hall. While another Location: Athabaskan Exhibit is missing.

Thanks for working on this project. If there would be a Howto (that explains how to add cards) to this project. I might pitch in to add some playercards from time to time.

**Comment by llebel** [comment]
Hi, thanks for the feedback !
Will have a look at this missing location tonight.

Regarding actual documentation for adding cards, you can find it on [OCTGN wiki](https://github.com/octgn/OCTGN/wiki) section *CREATE GAMES ON OCTGN* chapter [set.xml](https://github.com/octgn/OCTGN/wiki/set.xml)

**Comment by rushl** [comment]
This is resolved with [PR 117](https://github.com/GeckoTH/arkham-horror/pull/117).
