### ISSUE TITLE
Windows detects "Trojan:Script/Foretype.A!ml" in AHLCG-DB.xlsm

### ISSUE THREAD

**Issue by wlk0** [GeckoTH/arkham-horror#121]

**Comment by PlaidOsyluth** [comment]
Could you provide the program which reported the Trojan? I've scanned the file with Symantec, Windows Defender, and Malwarebytes, and it is reported as clean with those tools.

**Comment by wlk0** [comment]
I just tried to download the repo as a ZIP, and Windows Defender triggered the alert.

**Comment by PlaidOsyluth** [comment]
Can this issue be closed with the latest release?

**Comment by wlk0** [comment]
Yes, seems fine now.
Thanks !
