### ISSUE TITLE
Incorrect Card Back

### ISSUE THREAD

**Issue by FlyingMuttley** [GeckoTH/arkham-horror#124]
The Man in the Pallid Mask has an encounter card back rather than player card.

**Comment by PlaidOsyluth** [comment]
This should be resolved once PR #126 is merged.

**Comment by PlaidOsyluth** [comment]
@FlyingMuttley 
The code has been merged (although a new release is still pending).  Could you please check with the latest set.xml file obtained from GitHub and check that it works for you?  Thanks!
