### ISSUE TITLE
Load Table State duplicates all hand cards

### ISSUE THREAD

**Issue by calculuschild** [GeckoTH/arkham-horror#160]
As stated in the title. Willing to provide more information but not sure what would be helpful.

**Comment by ChristopherS** [comment]
When Innsmouth comes out, I will have to code in the new mechanics anyway. I will take a closer look then. However I cannot promise anything. The tablestate saving code is a bit dodgy. If I need more Information, I will tell you.

**Comment by rushl** [comment]
Resolved via PR #167
