### ISSUE TITLE
How install game on OCTGN

### ISSUE THREAD

**Issue by unfelion** [GeckoTH/arkham-horror#24]
Hi. To test the script I want to know how to install the game on OCTGN. I downloaded the script but do not know how to add a feed.
Thank you for your work and greetings.

**Comment by wlk0** [comment]
You need to package it into OCTGN local feed, using o8build.exe /i /d <path to the git repo>, then enable it in OCTGN game manager (local feed).

**Comment by unfelion** [comment]
Wich is git repo path ?
