### ISSUE TITLE
MIssing Cards in "The Scarlet Keys Campaign Expansion" set

### ISSUE THREAD

**Issue by ashltd** [GeckoTH/arkham-horror#261]
Hi,

I've been checking the set for "The Scarlet Keys Campaign Expansion" module and I found that Card 247 (City of Remnants/Rambling Route) appears only once when the physical version contains 3 different copies (it's the same "b" side, but different "a" side).

The same happens for card 250 (City of Remnants/Cliffs of Insanity)

**Comment by KenDdoox** [comment]
Ah, got it. I'll update it in the next patch.

**Comment by ashltd** [comment]
Hi @KenDdoox, @rushl,

Thanks a lot!
