### ISSUE TITLE
Error message if different player load encounter deck and chaos bag

### ISSUE THREAD

**Issue by brackis** [GeckoTH/arkham-horror#41]
if one player load the encounter deck and another one load the chaos bag you have an error message who say that 
setcontroller could not be applied to a pile
setcontroller work only with a group

i am sorry if it is not clear i will post the complete error message tomorrow.

**Comment by hone** [comment]
Thanks for the report. I'll try to take a look at that. We still need to do a lot of testing/clean up work for handling MP properly.

**Comment by brackis** [comment]
i am not dev but if i can help you tell me

I think the problem is due to theese line

    if isShared:
        notify("{} Takes control of the encounter deck".format(me))
        for p in shared.piles:
            if shared.piles[p].controller != me:
                shared.piles[p].setController(me)

setcontroller(player) dont work on pile
it work on group

for changing card controller it is
card.controller = player
