### ISSUE TITLE
Discard card into a pile you don't own

### ISSUE THREAD

**Issue by brackis** [GeckoTH/arkham-horror#50]
you have a little error in action.py

in def discard

Line 1566
card.setController(who)  

the correct synthax for changing card controller is
card.Controller = who

with your line it is impossible to discard an encounter card if you are not the own of encounter discard pile

furthermore, i suggest to add mute()
line 1603 in def doDiscard

**Comment by brackis** [comment]
oups little mistake i have edited my first comment

**Comment by hone** [comment]
Fixed by #51
