### ISSUE TITLE
isSpecialCard script exception

### ISSUE THREAD

**Issue by wlk0** [GeckoTH/arkham-horror#52]
Minor issue, but when trying to shuffle encounter cards from the table (put there by setup), a call to an undefined "_isSpecialCard_" triggers an exception.
I guess it's the one left in "_shuffleIntoDeck_".

**Comment by brackis** [comment]
i have tested and yes if you remove the two line
    elif isSpecialCard(card):
        pile = specialDeck()

The exeption is fixed

Furthermore the line 
card.setcontroller(who)
also return an error.
card.controller = who seems to work

**Comment by hone** [comment]
Fixed by #54
