### ISSUE TITLE
Dunwich Legacy Basic Weakness Types are Wrong

### ISSUE THREAD

**Issue by hone** [GeckoTH/arkham-horror#88]
The Dunwich Legacy Basic Weaknesses use the wrong back when flipped because they hold the wrong [Subtype value](https://github.com/GeckoTH/arkham-horror/blob/master/o8g/Sets/Dunwich%20Legacy/set.xml#L480). Instead of `basicweakness` it should be `Basic Weakness` like the [Core Set](https://github.com/GeckoTH/arkham-horror/blob/master/o8g/Sets/Core%20Set/set.xml#L1108). /cc @rushl

**Comment by GeckoTH** [comment]
Fixed.
