### ISSUE TITLE
Carnivale of Horrors needs a "Campaign Deck" version

### ISSUE THREAD

**Issue by GeckoTH** [GeckoTH/arkham-horror#93]
The two Carnivale Decks currently in the folder (Standard and Hard mode) both include the Chaos Bag. We simply need to create an .08d of just the Scenario cards but no Chaos Bag, so players can load in their own campaign bag when playing this scenario as a side-quest.

**Comment by Khudzlin** [comment]
I made one, but I'm not sure how to separate that change from my other pull request (card data for Miskatonic Museum).

**Comment by rushl** [comment]
Implemented with commit #8fb0dee.
