### ISSUE TITLE
game site URL points to dead domain

### ISSUE THREAD

**Issue by brine** [GeckoTH/arkham-horror#94]
hey, I noticed that the game site in the XML is pointing to a page on gamersjudgement, that domain has been dead for a while now.  Should be pointing to the octgngames domain.

**Comment by GeckoTH** [comment]
Thanks brine! Will fix in the next push

**Comment by brine** [comment]
Oh wow I'm dumb, I haven't actually set up a page for the game yet.  I'll do that tonight.

**Comment by GeckoTH** [comment]
Thanks! I was gonna hop in IRC at some point to request a wordpress site for the game. I'm already an admin for the LOTR page, dunno if you're able to simply add me as an admin to the Arkham page as well.

**Comment by brine** [comment]
yeah hop in any time, wanted to ask about the image packs anyway

**Comment by GeckoTH** [comment]
URL has been fixed. Just gotta build the actual site now! ;)
