### ISSUE TITLE
Card backs

### ISSUE THREAD

**Issue by Khudzlin** [GeckoTH/arkham-horror#96]
Card back isn't entirely determined by type and subtype. There are assets with an encounter card back that need to be shuffled with encounter cards ("Jazz" Mulligan, Helpless Passenger and Key to the Chamber). I suggest adding a "Deck" column to the card data spreadsheet so that the correct size attribute can be assigned to each card.

**Comment by rushl** [comment]
There is actually already a provision for this, although it's not used often. If you look in the AHLCG-DB.xlsm file, all the way to the right, there's a column called Force Card Size (the header is orange). In the module, the "card size" property controls some of the basic card definitions, including simple backs. If you input "EncounterCard" in that field, the back of the card will be forced to the encounter backs. 

When exporting from the Excel file to the set.xml, the export process tags Encounter cards automatically with the size="EncounterCard" property. Using the Force column allows you to tag any card with a size property that it wouldn't normally get. 

The only instance it's been used (before Jazz) was for the Helpless Passenger in ECE. I'll go ahead and fix Jazz, and get that merged. Do you know of any others that need fixing?

Thanks!
Tim

**Comment by Khudzlin** [comment]
Nice. I believe the only other card which needs its size forced is Key to the Chamber (Blood on the Altar).

**Comment by rushl** [comment]
Jazz, Peter Clover, Adam Lynch, Harold Walstead, and the Alchemical Concoction now have the proper encounter backs!
